"""embedding dim change

Revision ID: 4306e4fb741a
Revises: be82e5fabb5f
Create Date: 2026-05-18 07:19:50.441869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '4306e4fb741a'
down_revision: Union[str, Sequence[str], None] = 'be82e5fabb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_embeddings', 'structured_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=786),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.alter_column('product_embeddings', 'generated_description_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=786),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_embeddings', 'generated_description_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=786),
               existing_nullable=False)
    op.alter_column('product_embeddings', 'structured_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=786),
               existing_nullable=False)
    # ### end Alembic commands ###
