"""review_text rename

Revision ID: 9435123a7c43
Revises: 4306e4fb741a
Create Date: 2026-05-18 07:28:43.076762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '9435123a7c43'
down_revision: Union[str, Sequence[str], None] = '4306e4fb741a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('reviews', 'review_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'text')
    # ### end Alembic commands ###
