"""added task_uuid column

Revision ID: c86c8ef111fd
Revises: 82d2664e3a0e
Create Date: 2026-05-22 09:03:06.211314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'c86c8ef111fd'
down_revision: Union[str, Sequence[str], None] = '82d2664e3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('tasks', 'callback_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_tasks_task_uuid'), 'tasks', ['task_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_uuid'), table_name='tasks')
    op.alter_column('tasks', 'callback_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tasks', 'task_uuid')
    # ### end Alembic commands ###
